name: Submit

on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  submit:
    name: Submit to Kaggle
    environment: kaggle
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install Kaggle CLI
        run: |
          python -m pip install --upgrade pip
          pip install kaggle

      - name: Submit to Kaggle
        run: |
          kaggle competitions submit hill-of-towie-wind-turbine-power-prediction \
          -k notebooks/submission \
          -f submission.csv \
          -v 1 \
          -m "Hill of Tower Power Prediction using Stacked Power Predictors"
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
