name: Submit

on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  submit:
    name: Push to Kaggle
    environment: kaggle
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install Kaggle CLI
        run: |
          python -m pip install --upgrade pip
          pip install kaggle

      - name: Push Kernel to Kaggle
        run: |
          kaggle kernels push -p notebooks/submissions
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
